repository_type: pipeline

nf_core_version: 3.2.0

lint:
  multiqc_config: False
  included_configs: False
  files_exist: 
    - assets/email_template.html
    - assets/email_template.txt


template:
  org: nf-core
  name: nfmitnanext
  description: mitochondrial nanopore reads extractor
  author: juanjo255
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
