repository_type: pipeline

nf_core_version: 3.2.0

lint: {}

template:
  org: nf-core
  name: nfmitnanext
  description: mitochondrial nanopore reads extractor
  author: juanjo55
  version: 1.0.0dev
  force: true
  outdir: .
  is_nfcore: true
