input: '${projectDir}/sample_data/samples.csv'
outdir: 'results'
fasta: '${projectDir}/sample_data/candida_mitochondria.fasta'
contamination_fasta: '${projectDir}/sample_data/fake_contamination.fasta'
min_mapQ: 15
flye_mode: '--nano-hq'
ref_gff: '${projectDir}/sample_data/candida_mitochondria_test_annotation.gff3'